// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mcsimex_sim_cpp
Rcpp::NumericMatrix mcsimex_sim_cpp(Rcpp::NumericVector y_r, Rcpp::IntegerVector z_hat_r, Rcpp::NumericMatrix x_r, Rcpp::NumericMatrix Pi_r, int K, int dist_code, Rcpp::NumericVector lambda_r, int B, Rcpp::NumericVector wt_r, unsigned int seed);
RcppExport SEXP _mismeasured_mcsimex_sim_cpp(SEXP y_rSEXP, SEXP z_hat_rSEXP, SEXP x_rSEXP, SEXP Pi_rSEXP, SEXP KSEXP, SEXP dist_codeSEXP, SEXP lambda_rSEXP, SEXP BSEXP, SEXP wt_rSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_r(y_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type z_hat_r(z_hat_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Pi_r(Pi_rSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type dist_code(dist_codeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_r(lambda_rSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wt_r(wt_rSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(mcsimex_sim_cpp(y_r, z_hat_r, x_r, Pi_r, K, dist_code, lambda_r, B, wt_r, seed));
    return rcpp_result_gen;
END_RCPP
}
// mcsimex_multi_sim_cpp
Rcpp::NumericMatrix mcsimex_multi_sim_cpp(Rcpp::NumericVector y_r, Rcpp::List z_list, Rcpp::List Pi_list, Rcpp::IntegerVector K_vec, Rcpp::NumericMatrix x_r, int dist_code, Rcpp::NumericVector lambda_r, int B, Rcpp::NumericVector wt_r, unsigned int seed);
RcppExport SEXP _mismeasured_mcsimex_multi_sim_cpp(SEXP y_rSEXP, SEXP z_listSEXP, SEXP Pi_listSEXP, SEXP K_vecSEXP, SEXP x_rSEXP, SEXP dist_codeSEXP, SEXP lambda_rSEXP, SEXP BSEXP, SEXP wt_rSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_r(y_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type z_list(z_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Pi_list(Pi_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type K_vec(K_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< int >::type dist_code(dist_codeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_r(lambda_rSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wt_r(wt_rSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(mcsimex_multi_sim_cpp(y_r, z_list, Pi_list, K_vec, x_r, dist_code, lambda_r, B, wt_r, seed));
    return rcpp_result_gen;
END_RCPP
}
// simex_sim_cpp
Rcpp::NumericMatrix simex_sim_cpp(Rcpp::NumericVector y_r, Rcpp::NumericMatrix X_r, Rcpp::IntegerVector simex_cols_r, Rcpp::NumericMatrix me_r, int dist_code, Rcpp::NumericVector lambda_r, int B, Rcpp::NumericVector wt_r, unsigned int seed);
RcppExport SEXP _mismeasured_simex_sim_cpp(SEXP y_rSEXP, SEXP X_rSEXP, SEXP simex_cols_rSEXP, SEXP me_rSEXP, SEXP dist_codeSEXP, SEXP lambda_rSEXP, SEXP BSEXP, SEXP wt_rSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_r(y_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_r(X_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type simex_cols_r(simex_cols_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type me_r(me_rSEXP);
    Rcpp::traits::input_parameter< int >::type dist_code(dist_codeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_r(lambda_rSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wt_r(wt_rSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(simex_sim_cpp(y_r, X_r, simex_cols_r, me_r, dist_code, lambda_r, B, wt_r, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mismeasured_mcsimex_sim_cpp", (DL_FUNC) &_mismeasured_mcsimex_sim_cpp, 10},
    {"_mismeasured_mcsimex_multi_sim_cpp", (DL_FUNC) &_mismeasured_mcsimex_multi_sim_cpp, 10},
    {"_mismeasured_simex_sim_cpp", (DL_FUNC) &_mismeasured_simex_sim_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_mismeasured(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
