#' Bias-Corrected GLM Estimation with Misclassified Covariates
#'
#' Fits a GLM where one covariate is observed with misclassification error and
#' applies bias corrections following Battaglia et al. (2025). Supports binary
#' and multicategory misclassified covariates and five estimation methods:
#' naive, BCA (additive bias correction), BCM (multiplicative bias correction),
#' CS (corrected score), and one-step (joint mixture-likelihood via RTMB).
#'
#' @param formula Either a formula of the form \code{y ~ mc(z, Pi) + x1 + x2}
#'   (where \code{mc()} marks the misclassified covariate with its
#'   misclassification matrix), or a numeric response vector (for the
#'   matrix interface).
#' @param data A data frame (required when using the formula interface).
#' @param family A \code{\link[stats]{family}} object or one of
#'   \code{"poisson"}, \code{"binomial"}, \code{"gaussian"},
#'   \code{"multinomial"}.
#' @param method Character vector of methods to compute. Any subset of
#'   \code{c("naive", "bca", "bcm", "cs", "onestep")}.
#' @param p01 False-positive rate P(Z_hat = 1 | Z = 0). For binary case;
#'   if \code{Pi} is provided, extracted automatically.
#' @param p10 False-negative rate P(Z_hat = 0 | Z = 1). For binary case;
#'   if \code{Pi} is provided, extracted automatically.
#' @param pi_z Prevalence P(Z = 1) (binary) or K-vector of class prevalences
#'   (multicategory). Required for correction methods.
#' @param Pi K x K misclassification matrix. When using the formula interface,
#'   this is extracted from the \code{mc()} term. Columns must sum to 1:
#'   \code{Pi[j, l] = P(Z_hat = j-1 | Z = l-1)}.
#' @param K Number of categories. Auto-detected if \code{NULL}.
#' @param c1 Pre-computed misclassification constant \eqn{c_1 = p_{01}(1-\pi_z)}.
#'   For binary case; computed automatically from \code{p01} and \code{pi_z}
#'   if not supplied directly.
#' @param c2 Pre-computed misclassification constant
#'   \eqn{c_2 = p_{01}(1-\pi_z) - p_{10}\pi_z}.
#'   For binary case; computed automatically from \code{p01}, \code{p10},
#'   and \code{pi_z} if not supplied directly.
#' @param iterate Logical. If \code{TRUE}, iterate BCA/BCM until convergence.
#' @param fix_omega Logical. If \code{TRUE}, fix the mixture weights (omega) at
#'   the values implied by the supplied misclassification parameters (onestep
#'   only). Default \code{FALSE} estimates omega jointly.
#' @param weights Optional frequency weights vector (length n, positive).
#' @param J Number of response categories for multinomial. Auto-detected.
#' @param homoskedastic Logical. For Gaussian one-step, assume common variance.
#' @param optim_control List of control parameters for \code{nlminb} (onestep).
#' @param z_hat Integer vector of observed proxy covariate (matrix interface).
#' @param x Covariate matrix including intercept (matrix interface).
#'
#' @return An object of class \code{"mcglm"}, a list with components:
#'   \describe{
#'     \item{coefficients}{Named list of coefficient vectors, one per method.}
#'     \item{naive_fit}{The \code{glm} object from the naive fit.}
#'     \item{method}{Methods used.}
#'     \item{family}{The GLM family.}
#'     \item{K}{Number of categories.}
#'     \item{n, p}{Sample size and number of parameters.}
#'     \item{weights}{Frequency weights used (NULL if unweighted).}
#'     \item{vcov_onestep}{Variance-covariance matrix (if onestep used).}
#'     \item{loglik_onestep}{Log-likelihood at one-step estimate.}
#'   }
#'
#' @references
#' Battaglia, L., Christensen, T., Hansen, S. and Sacher, S. (2025).
#' Inference for regression with variables generated by AI or machine
#' learning. \emph{arXiv preprint arXiv:2402.15585}.
#'
#' @examples
#' # --- Formula interface ---
#' set.seed(42)
#' n <- 2000
#' Pi <- matrix(c(0.9, 0.1, 0.15, 0.85), 2, 2)
#' z <- rbinom(n, 1, 0.4)
#' z_hat <- z
#' z_hat[z == 0] <- rbinom(sum(z == 0), 1, 0.10)
#' z_hat[z == 1] <- 1 - rbinom(sum(z == 1), 1, 0.15)
#' x1 <- rnorm(n)
#' y <- rpois(n, exp(0.8 * z + -0.5 + 0.7 * x1))
#' df <- data.frame(y = y, z = factor(z_hat), x1 = x1)
#'
#' fit <- mcglm(y ~ mc(z, Pi) + x1, data = df, family = "poisson")
#' fit
#'
#' # --- Matrix interface ---
#' x_mat <- cbind(1, x1)
#' fit2 <- mcglm(y, z_hat = as.integer(z_hat), x = x_mat,
#'               family = "poisson", p01 = 0.10, p10 = 0.15, pi_z = 0.4)
#'
#' @export
mcglm <- function(formula, data = NULL, family = "poisson",
                  method = c("naive", "bca", "bcm", "cs"),
                  p01 = NULL, p10 = NULL, pi_z = NULL,
                  Pi = NULL, K = NULL,
                  c1 = NULL, c2 = NULL,
                  iterate = FALSE,
                  fix_omega = FALSE,
                  weights = NULL,
                  J = NULL,
                  homoskedastic = TRUE,
                  optim_control = list(),
                  z_hat = NULL, x = NULL) {

  # --- Dispatch: formula vs matrix interface ---
  if (inherits(formula, "formula")) {
    caller_env <- parent.frame()
    parsed <- .mcglm_parse_formula(formula, data, caller_env)
    y     <- parsed$y
    z_hat <- parsed$z_hat
    x     <- parsed$x
    if (is.null(Pi) && !is.null(parsed$Pi)) Pi <- parsed$Pi
    if (is.null(K))  K  <- parsed$K
  } else {
    # Matrix interface: first arg is y
    y <- formula
  }

  # --- Derive p01/p10 from 2x2 Pi ---
  if (!is.null(Pi) && nrow(Pi) == 2L) {
    if (is.null(p01)) p01 <- Pi[2, 1]
    if (is.null(p10)) p10 <- Pi[1, 2]
  }

  # --- Estimate pi_z from observed data + Pi if not supplied ---
  if (is.null(pi_z) && !is.null(Pi) && !is.null(z_hat)) {
    pi_z <- .mcglm_estimate_pi_z(z_hat, Pi)
  }

  # --- Derive c1/c2 from (p01, p10, pi_z) if not supplied directly ---
  if (is.null(c1) && !is.null(p01) && !is.null(pi_z))
    c1 <- p01 * (1 - pi_z)
  if (is.null(c2) && !is.null(p01) && !is.null(p10) && !is.null(pi_z))
    c2 <- p01 * (1 - pi_z) - p10 * pi_z

  # --- Core fitting ---
  .mcglm_fit(y = y, z_hat = z_hat, x = x, family = family,
             method = method, p01 = p01, p10 = p10, pi_z = pi_z,
             Pi = Pi, K = K, c1 = c1, c2 = c2, iterate = iterate,
             fix_omega = fix_omega, weights = weights, J = J,
             homoskedastic = homoskedastic, optim_control = optim_control)
}


#' Parse mcglm formula extracting mc() term
#' @keywords internal
.mcglm_parse_formula <- function(formula, data, env) {
  if (is.null(data))
    stop("'data' argument is required when using the formula interface.")

  lhs <- formula[[2]]
  rhs <- formula[[3]]

  # Extract response
  y_name <- deparse(lhs)
  y <- data[[y_name]]
  if (is.null(y))
    stop("Response variable '", y_name, "' not found in data.")


  # Walk RHS to find mc() term and other covariates
  mc_info <- NULL
  other_terms <- character(0)

  .walk_mcglm_rhs <- function(node) {
    if (is.call(node)) {
      op <- deparse(node[[1]])
      if (op == "+") {
        .walk_mcglm_rhs(node[[2]])
        .walk_mcglm_rhs(node[[3]])
        return(invisible(NULL))
      }
      if (op == "mc") {
        var_name <- deparse(node[[2]])
        if (length(node) >= 3L) {
          mat_val <- eval(node[[3]], data, env)
          mc_info <<- list(variable = var_name, Pi = as.matrix(mat_val))
        } else {
          mc_info <<- list(variable = var_name, Pi = NULL)
        }
        return(invisible(NULL))
      }
    }
    # Everything else is a regular term
    other_terms <<- c(other_terms, deparse(node))
    invisible(NULL)
  }

  .walk_mcglm_rhs(rhs)

  if (is.null(mc_info))
    stop("Formula must contain exactly one mc() term, e.g., y ~ mc(z, Pi) + x")

  # Get z_hat from data
  z_var <- data[[mc_info$variable]]
  if (is.null(z_var))
    stop("mc() variable '", mc_info$variable, "' not found in data.")

  Pi <- mc_info$Pi

  # Convert z to 0-based integer
  if (is.factor(z_var)) {
    z_hat <- as.integer(z_var) - 1L
  } else {
    z_hat <- as.integer(z_var)
  }

  # Determine K
  K <- if (!is.null(Pi)) nrow(Pi) else length(unique(z_hat))

  # Validate Pi when provided
  if (!is.null(Pi)) {
    if (ncol(Pi) != K)
      stop("Pi must be a square K x K matrix (got ", nrow(Pi), " x ", ncol(Pi), ").")
    cs <- colSums(Pi)
    if (any(abs(cs - 1) > 1e-6))
      stop("Columns of Pi must sum to 1 (got: ",
           paste(round(cs, 4), collapse = ", "), ").")
  }

  # Build x matrix from remaining terms
  if (length(other_terms) == 0) {
    # No other covariates: just intercept
    x <- matrix(1, nrow = nrow(data), ncol = 1)
  } else {
    rhs_formula <- as.formula(paste("~", paste(other_terms, collapse = " + ")),
                              env = env)
    x <- model.matrix(rhs_formula, data = data)
  }

  list(y = as.numeric(y), z_hat = z_hat, x = x, Pi = Pi, K = K)
}


#' Core mcglm fitting (internal, called by mcglm after dispatch)
#' @keywords internal
.mcglm_fit <- function(y, z_hat, x, family = "poisson",
                       method = c("naive", "bca", "bcm", "cs"),
                       p01 = NULL, p10 = NULL, pi_z = NULL,
                       Pi = NULL, K = NULL,
                       c1 = NULL, c2 = NULL,
                       iterate = FALSE,
                       fix_omega = FALSE,
                       weights = NULL,
                       J = NULL,
                       homoskedastic = TRUE,
                       optim_control = list()) {

  # --- input validation ---
  y     <- as.numeric(y)
  z_hat <- as.integer(z_hat)
  x     <- as.matrix(x)
  n     <- length(y)
  method <- match.arg(method, c("naive", "bca", "bcm", "cs", "onestep"),
                      several.ok = TRUE)

  stopifnot(nrow(x) == n, length(z_hat) == n)

  # --- validate frequency weights ---
  wt <- NULL
  if (!is.null(weights)) {
    wt <- as.numeric(weights)
    if (length(wt) != n)
      stop("weights must have length n (", n, "), got ", length(wt))
    if (any(wt <= 0))
      stop("weights must be positive")
  }

  # --- multinomial family ---
  is_multinomial <- is.character(family) && family == "multinomial"
  if (is_multinomial) {
    unsupported <- setdiff(method, c("naive", "onestep"))
    if (length(unsupported) > 0)
      stop("For multinomial family, only 'naive' and 'onestep' methods are ",
           "supported. Unsupported: ", paste(unsupported, collapse = ", "))
    y <- as.integer(y)
    if (is.null(J)) J <- length(unique(y))
    if (any(y < 0L) || any(y >= J))
      stop("For multinomial, y must be integers in {0, ..., J-1}")
  }

  # Determine binary vs multicategory
  if (is.null(K)) {
    unique_z <- sort(unique(z_hat))
    if (is.null(Pi) && all(unique_z %in% c(0L, 1L))) {
      K <- 2L
    } else {
      K <- length(unique_z)
    }
  }
  is_binary <- (K == 2L)

  # --- validate misclassification parameters ---
  needs_correction <- any(method %in% c("bca", "bcm", "cs", "onestep"))
  if (needs_correction) {
    if (is_binary) {
      needs_bca_bcm_cs <- any(method %in% c("bca", "bcm", "cs"))
      needs_onestep    <- "onestep" %in% method
      if (needs_bca_bcm_cs && (is.null(c1) || is.null(c2)))
        stop("For binary bca/bcm/cs, supply c1 and c2 (or Pi, or p01/p10/pi_z).")
      if (needs_onestep && fix_omega && (is.null(p01) || is.null(p10) || is.null(pi_z)))
        stop("For onestep with fix_omega=TRUE, supply p01, p10, and pi_z.")
    } else {
      needs_bca_bcm_cs <- any(method %in% c("bca", "bcm", "cs"))
      needs_onestep    <- "onestep" %in% method
      if (needs_bca_bcm_cs) {
        if (is.null(Pi) || is.null(pi_z))
          stop("For multicategory bca/bcm/cs, supply Pi and pi_z.")
        Pi   <- as.matrix(Pi)
        pi_z <- as.numeric(pi_z)
        stopifnot(nrow(Pi) == K, ncol(Pi) == K, length(pi_z) == K)
      }
      if (needs_onestep && fix_omega && (is.null(Pi) || is.null(pi_z)))
        stop("For multicategory onestep with fix_omega=TRUE, supply Pi and pi_z.")
    }
  }

  # --- build xi_hat once ---
  if (!is_multinomial) {
    xi_hat <- .mcglm_build_xi_hat(z_hat, x, K)
  }

  # --- fit ---
  results <- list()
  onestep_vcov   <- NULL
  onestep_loglik <- NULL
  naive_glm_fit  <- NULL

  if (is_multinomial) {
    naive_mn <- .mcglm_fit_naive_multinomial(y, z_hat, x, J, K, wt = wt)
    psi      <- naive_mn$coefficients
    results$naive <- psi
    p_total  <- length(psi)

    if ("onestep" %in% method) {
      os <- .mcglm_fit_onestep_multinomial(y, z_hat, x, J, K,
                                           p01 = p01, p10 = p10, pi_z = pi_z,
                                           Pi = Pi, fix_omega = fix_omega,
                                           optim_control = optim_control,
                                           wt = wt)
      results$onestep <- os$coefficients
      onestep_vcov    <- os$vcov
      onestep_loglik  <- os$loglik
    }

  } else if (is_binary) {
    naive <- .mcglm_fit_naive_bin(y, xi_hat, family, wt = wt)
    psi   <- naive$coefficients
    results$naive <- psi
    p_total <- length(psi)
    naive_glm_fit <- naive$glm_fit

    if ("bca" %in% method)
      results$bca <- .mcglm_fit_bca_bin(psi, y, xi_hat, x, family, c1, c2,
                                         iterate = iterate, wt = wt)
    if ("bcm" %in% method)
      results$bcm <- .mcglm_fit_bcm_bin(psi, y, xi_hat, x, family, c1, c2,
                                         iterate = iterate, wt = wt)
    if ("cs"  %in% method)
      results$cs  <- .mcglm_fit_cs_bin(psi, y, xi_hat, x, family, c1, c2,
                                        wt = wt)

    if ("onestep" %in% method) {
      os <- .mcglm_fit_onestep_bin(y, z_hat, x, family, p01, p10, pi_z,
                                   fix_omega = fix_omega,
                                   homoskedastic = homoskedastic,
                                   optim_control = optim_control, wt = wt)
      results$onestep <- os$coefficients
      onestep_vcov    <- os$vcov
      onestep_loglik  <- os$loglik
    }

  } else {
    naive <- .mcglm_fit_naive_multi(y, xi_hat, family, wt = wt)
    psi   <- naive$coefficients
    results$naive <- psi
    p_total <- length(psi)
    naive_glm_fit <- naive$glm_fit

    if ("bca" %in% method)
      results$bca <- .mcglm_fit_bca_multi(psi, y, xi_hat, z_hat, x, K, family,
                                           Pi, pi_z, iterate = iterate, wt = wt)
    if ("bcm" %in% method)
      results$bcm <- .mcglm_fit_bcm_multi(psi, y, xi_hat, z_hat, x, K, family,
                                           Pi, pi_z, iterate = iterate, wt = wt)
    if ("cs"  %in% method)
      results$cs  <- .mcglm_fit_cs_multi(psi, y, xi_hat, z_hat, x, K, family,
                                          Pi, pi_z, wt = wt)

    if ("onestep" %in% method) {
      os <- .mcglm_fit_onestep_multi(y, z_hat, x, K, family, Pi, pi_z,
                                     fix_omega = fix_omega,
                                     homoskedastic = homoskedastic,
                                     optim_control = optim_control, wt = wt)
      results$onestep <- os$coefficients
      onestep_vcov    <- os$vcov
      onestep_loglik  <- os$loglik
    }
  }

  # --- parameter names ---
  if (is_multinomial) {
    s <- K - 1
    r <- ncol(x)
    block_size <- s + r
    nms <- character(p_total)
    for (jj in seq_len(J - 1)) {
      offset <- (jj - 1) * block_size
      if (s == 1) {
        nms[offset + 1] <- paste0("y", jj, ":gamma")
      } else if (s > 1) {
        nms[offset + seq_len(s)] <- paste0("y", jj, ":gamma", seq_len(s))
      }
      nms[offset + s + seq_len(r)] <- paste0("y", jj, ":alpha", seq_len(r) - 1)
    }
  } else if (is_binary) {
    nms <- c("gamma", paste0("alpha", seq_len(ncol(x)) - 1))
  } else {
    nms <- c(paste0("gamma", seq_len(K - 1)),
             paste0("alpha", seq_len(ncol(x)) - 1))
  }
  results <- lapply(results, function(v) {
    if (is.null(names(v))) names(v) <- nms
    v
  })

  out <- list(
    coefficients = results,
    naive_fit    = naive_glm_fit,
    method       = method,
    family       = family,
    K            = K,
    n            = n,
    p            = p_total,
    weights      = wt
  )
  if (is_multinomial) out$J <- J

  if (!is.null(onestep_vcov)) {
    out$vcov_onestep   <- onestep_vcov
    out$loglik_onestep <- onestep_loglik
  }

  structure(out, class = "mcglm")
}


#' @export
print.mcglm <- function(x, digits = 4, ...) {
  cat("Bias-corrected GLM with misclassified covariate\n")
  cat(sprintf("  n = %d, p = %d, K = %d\n\n", x$n, x$p, x$K))

  coefs <- do.call(cbind, x$coefficients)
  colnames(coefs) <- toupper(names(x$coefficients))
  print(round(coefs, digits))
  invisible(x)
}

#' @export
coef.mcglm <- function(object, method = NULL, ...) {
  if (is.null(method)) return(object$coefficients)
  object$coefficients[[method]]
}

#' @export
vcov.mcglm <- function(object, ...) {
  object$vcov_onestep
}

#' @export
summary.mcglm <- function(object, ...) {
  cat("Bias-corrected GLM with misclassified covariate\n")
  cat(sprintf("  Family: %s\n", if (is.character(object$family))
    object$family else object$family$family))
  cat(sprintf("  n = %d, p = %d, K = %d\n", object$n, object$p, object$K))
  cat(sprintf("  Methods: %s\n\n", paste(object$method, collapse = ", ")))

  coefs <- do.call(cbind, object$coefficients)
  colnames(coefs) <- toupper(names(object$coefficients))
  cat("Coefficients:\n")
  print(round(coefs, 6))

  if (length(object$coefficients) > 1) {
    cat("\nBias correction (difference from naive):\n")
    naive <- object$coefficients$naive
    diffs <- sapply(object$coefficients[-1], function(v) v - naive)
    if (!is.matrix(diffs)) diffs <- matrix(diffs, nrow = 1)
    rownames(diffs) <- names(naive)
    print(round(diffs, 6))
  }

  invisible(object)
}
