#' Bias-Corrected GLM Estimation with Misclassified Covariates
#'
#' Fits a GLM where one covariate is observed with misclassification error and
#' applies bias corrections following Battaglia et al. (2025). Supports binary
#' and multicategory misclassified covariates and five estimation methods:
#' naive, BCA (additive bias correction), BCM (multiplicative bias correction),
#' CS (corrected score), and one-step (joint mixture-likelihood via RTMB).
#'
#' @param formula Either a formula of the form \code{y ~ mc(z, Pi) + x1 + x2}
#'   (where \code{mc()} marks the misclassified covariate with its
#'   misclassification matrix), or a numeric response vector (for the
#'   matrix interface).
#' @param data A data frame (required when using the formula interface).
#' @param family A \code{\link[stats]{family}} object or one of
#'   \code{"poisson"}, \code{"binomial"}, \code{"gaussian"},
#'   \code{"multinomial"}.
#' @param method Character vector of methods to compute. Any subset of
#'   \code{c("naive", "bca", "bcm", "cs", "onestep")}.
#' @param p01 False-positive rate P(Z_hat = 1 | Z = 0). For binary case;
#'   if \code{Pi} is provided, extracted automatically.
#' @param p10 False-negative rate P(Z_hat = 0 | Z = 1). For binary case;
#'   if \code{Pi} is provided, extracted automatically.
#' @param pi_z Prevalence P(Z = 1) (binary) or K-vector of class prevalences
#'   (multicategory). Required for correction methods.
#' @param Pi K x K misclassification matrix. When using the formula interface,
#'   this is extracted from the \code{mc()} term. Columns must sum to 1:
#'   \code{Pi[j, l] = P(Z_hat = j-1 | Z = l-1)}.
#' @param K Number of categories. Auto-detected if \code{NULL}.
#' @param c1 Pre-computed misclassification constant \eqn{c_1 = p_{01}(1-\pi_z)}.
#'   For binary case; computed automatically from \code{p01} and \code{pi_z}
#'   if not supplied directly.
#' @param c2 Pre-computed misclassification constant
#'   \eqn{c_2 = p_{01}(1-\pi_z) - p_{10}\pi_z}.
#'   For binary case; computed automatically from \code{p01}, \code{p10},
#'   and \code{pi_z} if not supplied directly.
#' @param iterate Logical. If \code{TRUE}, iterate BCA/BCM until convergence.
#' @param fix_omega Logical. If \code{TRUE}, fix the mixture weights (omega) at
#'   the values implied by the supplied misclassification parameters (onestep
#'   only). Default \code{FALSE} estimates omega jointly.
#' @param vcov_corrected Logical. If \code{TRUE}, the BCA/BCM variance
#'   estimators account for the additional uncertainty due to estimating the
#'   drift correction term (joint score-and-drift sandwich). If \code{FALSE}
#'   (default), the asymptotic variance \eqn{A^{-1} C A^{-1}} from
#'   Theorem 5 of Battaglia et al. (2025) is used (drifting-regime sandwich
#'   evaluated at the corrected estimate).
#' @param weights Optional frequency weights vector (length n, positive).
#' @param J Number of response categories for multinomial. Auto-detected.
#' @param homoskedastic Logical. For Gaussian one-step, assume common variance.
#' @param optim_control List of control parameters for \code{nlminb} (onestep).
#' @param z_hat Integer vector of observed proxy covariate (matrix interface).
#' @param x Covariate matrix including intercept (matrix interface).
#'
#' @return An object of class \code{"mcglm"}, a list with components:
#'   \describe{
#'     \item{coefficients}{Named list of coefficient vectors, one per method.}
#'     \item{vcov}{Named list of asymptotic variance-covariance matrices,
#'       one per method (sandwich estimators from the paper's theorems).}
#'     \item{se}{Named list of standard errors per method.}
#'     \item{naive_fit}{The \code{glm} object from the naive fit.}
#'     \item{method}{Methods used.}
#'     \item{family}{The GLM family.}
#'     \item{K}{Number of categories.}
#'     \item{n, p}{Sample size and number of parameters.}
#'     \item{weights}{Frequency weights used (NULL if unweighted).}
#'     \item{loglik_onestep}{Log-likelihood at one-step estimate.}
#'     \item{call, formula}{The matched call and (if used) formula.}
#'   }
#'
#' @references
#' Battaglia, L., Christensen, T., Hansen, S. and Sacher, S. (2025).
#' Inference for regression with variables generated by AI or machine
#' learning. \emph{arXiv preprint arXiv:2402.15585}.
#'
#' @examples
#' # --- Formula interface ---
#' set.seed(42)
#' n <- 2000
#' Pi <- matrix(c(0.9, 0.1, 0.15, 0.85), 2, 2)
#' z <- rbinom(n, 1, 0.4)
#' z_hat <- z
#' z_hat[z == 0] <- rbinom(sum(z == 0), 1, 0.10)
#' z_hat[z == 1] <- 1 - rbinom(sum(z == 1), 1, 0.15)
#' x1 <- rnorm(n)
#' y <- rpois(n, exp(0.8 * z + -0.5 + 0.7 * x1))
#' df <- data.frame(y = y, z = factor(z_hat), x1 = x1)
#'
#' fit <- mcglm(y ~ mc(z, Pi) + x1, data = df, family = "poisson")
#' fit
#'
#' # --- Matrix interface ---
#' x_mat <- cbind(1, x1)
#' fit2 <- mcglm(y, z_hat = as.integer(z_hat), x = x_mat,
#'               family = "poisson", p01 = 0.10, p10 = 0.15, pi_z = 0.4)
#'
#' @export
mcglm <- function(formula, data = NULL, family = "poisson",
                  method = c("naive", "bca", "bcm", "cs"),
                  p01 = NULL, p10 = NULL, pi_z = NULL,
                  Pi = NULL, K = NULL,
                  c1 = NULL, c2 = NULL,
                  iterate = FALSE,
                  fix_omega = FALSE,
                  vcov_corrected = FALSE,
                  weights = NULL,
                  J = NULL,
                  homoskedastic = TRUE,
                  optim_control = list(),
                  z_hat = NULL, x = NULL) {

  cl <- match.call()
  formula_obj <- NULL

  # --- Dispatch: formula vs matrix interface ---
  if (inherits(formula, "formula")) {
    formula_obj <- formula
    caller_env <- parent.frame()
    parsed <- .mcglm_parse_formula(formula, data, caller_env)
    y     <- parsed$y
    z_hat <- parsed$z_hat
    x     <- parsed$x
    if (is.null(Pi) && !is.null(parsed$Pi)) Pi <- parsed$Pi
    if (is.null(K))  K  <- parsed$K
  } else {
    # Matrix interface: first arg is y
    y <- formula
  }

  # --- Derive p01/p10 from 2x2 Pi ---
  if (!is.null(Pi) && nrow(Pi) == 2L) {
    if (is.null(p01)) p01 <- Pi[2, 1]
    if (is.null(p10)) p10 <- Pi[1, 2]
  }

  # --- Estimate pi_z from observed data + Pi if not supplied ---
  if (is.null(pi_z) && !is.null(Pi) && !is.null(z_hat)) {
    pi_z <- .mcglm_estimate_pi_z(z_hat, Pi)
  }

  # --- Derive c1/c2 from (p01, p10, pi_z) if not supplied directly ---
  if (is.null(c1) && !is.null(p01) && !is.null(pi_z))
    c1 <- p01 * (1 - pi_z)
  if (is.null(c2) && !is.null(p01) && !is.null(p10) && !is.null(pi_z))
    c2 <- p01 * (1 - pi_z) - p10 * pi_z

  # --- Core fitting ---
  out <- .mcglm_fit(y = y, z_hat = z_hat, x = x, family = family,
                    method = method, p01 = p01, p10 = p10, pi_z = pi_z,
                    Pi = Pi, K = K, c1 = c1, c2 = c2, iterate = iterate,
                    fix_omega = fix_omega,
                    vcov_corrected = vcov_corrected,
                    weights = weights, J = J,
                    homoskedastic = homoskedastic,
                    optim_control = optim_control)
  out$call    <- cl
  out$formula <- formula_obj
  out
}


#' Parse mcglm formula extracting mc() term
#' @keywords internal
.mcglm_parse_formula <- function(formula, data, env) {
  if (is.null(data))
    stop("'data' argument is required when using the formula interface.")

  lhs <- formula[[2]]
  rhs <- formula[[3]]

  # Extract response
  y_name <- deparse(lhs)
  y <- data[[y_name]]
  if (is.null(y))
    stop("Response variable '", y_name, "' not found in data.")


  # Walk RHS to find mc() term and other covariates
  mc_info <- NULL
  other_terms <- character(0)

  .walk_mcglm_rhs <- function(node) {
    if (is.call(node)) {
      op <- deparse(node[[1]])
      if (op == "+") {
        .walk_mcglm_rhs(node[[2]])
        .walk_mcglm_rhs(node[[3]])
        return(invisible(NULL))
      }
      if (op == "mc") {
        var_name <- deparse(node[[2]])
        if (length(node) >= 3L) {
          mat_val <- eval(node[[3]], data, env)
          mc_info <<- list(variable = var_name, Pi = as.matrix(mat_val))
        } else {
          mc_info <<- list(variable = var_name, Pi = NULL)
        }
        return(invisible(NULL))
      }
    }
    # Everything else is a regular term
    other_terms <<- c(other_terms, deparse(node))
    invisible(NULL)
  }

  .walk_mcglm_rhs(rhs)

  if (is.null(mc_info))
    stop("Formula must contain exactly one mc() term, e.g., y ~ mc(z, Pi) + x")

  # Get z_hat from data
  z_var <- data[[mc_info$variable]]
  if (is.null(z_var))
    stop("mc() variable '", mc_info$variable, "' not found in data.")

  Pi <- mc_info$Pi

  # Convert z to 0-based integer
  if (is.factor(z_var)) {
    z_hat <- as.integer(z_var) - 1L
  } else {
    z_hat <- as.integer(z_var)
  }

  # Determine K
  K <- if (!is.null(Pi)) nrow(Pi) else length(unique(z_hat))

  # Validate Pi when provided
  if (!is.null(Pi)) {
    if (ncol(Pi) != K)
      stop("Pi must be a square K x K matrix (got ", nrow(Pi), " x ", ncol(Pi), ").")
    cs <- colSums(Pi)
    if (any(abs(cs - 1) > 1e-6))
      stop("Columns of Pi must sum to 1 (got: ",
           paste(round(cs, 4), collapse = ", "), ").")
  }

  # Build x matrix from remaining terms
  if (length(other_terms) == 0) {
    # No other covariates: just intercept
    x <- matrix(1, nrow = nrow(data), ncol = 1)
  } else {
    rhs_formula <- as.formula(paste("~", paste(other_terms, collapse = " + ")),
                              env = env)
    x <- model.matrix(rhs_formula, data = data)
  }

  list(y = as.numeric(y), z_hat = z_hat, x = x, Pi = Pi, K = K)
}


#' Core mcglm fitting (internal, called by mcglm after dispatch)
#' @keywords internal
.mcglm_fit <- function(y, z_hat, x, family = "poisson",
                       method = c("naive", "bca", "bcm", "cs"),
                       p01 = NULL, p10 = NULL, pi_z = NULL,
                       Pi = NULL, K = NULL,
                       c1 = NULL, c2 = NULL,
                       iterate = FALSE,
                       fix_omega = FALSE,
                       vcov_corrected = FALSE,
                       weights = NULL,
                       J = NULL,
                       homoskedastic = TRUE,
                       optim_control = list()) {

  # --- input validation ---
  y     <- as.numeric(y)
  z_hat <- as.integer(z_hat)
  x     <- as.matrix(x)
  n     <- length(y)
  method <- match.arg(method, c("naive", "bca", "bcm", "cs", "onestep"),
                      several.ok = TRUE)

  stopifnot(nrow(x) == n, length(z_hat) == n)

  # --- validate frequency weights ---
  wt <- NULL
  if (!is.null(weights)) {
    wt <- as.numeric(weights)
    if (length(wt) != n)
      stop("weights must have length n (", n, "), got ", length(wt))
    if (any(wt <= 0))
      stop("weights must be positive")
  }

  # --- multinomial family ---
  is_multinomial <- is.character(family) && family == "multinomial"
  if (is_multinomial) {
    unsupported <- setdiff(method, c("naive", "onestep"))
    if (length(unsupported) > 0)
      stop("For multinomial family, only 'naive' and 'onestep' methods are ",
           "supported. Unsupported: ", paste(unsupported, collapse = ", "))
    y <- as.integer(y)
    if (is.null(J)) J <- length(unique(y))
    if (any(y < 0L) || any(y >= J))
      stop("For multinomial, y must be integers in {0, ..., J-1}")
  }

  # Determine binary vs multicategory
  if (is.null(K)) {
    unique_z <- sort(unique(z_hat))
    if (is.null(Pi) && all(unique_z %in% c(0L, 1L))) {
      K <- 2L
    } else {
      K <- length(unique_z)
    }
  }
  is_binary <- (K == 2L)

  # --- validate misclassification parameters ---
  needs_correction <- any(method %in% c("bca", "bcm", "cs", "onestep"))
  if (needs_correction) {
    if (is_binary) {
      needs_bca_bcm_cs <- any(method %in% c("bca", "bcm", "cs"))
      needs_onestep    <- "onestep" %in% method
      if (needs_bca_bcm_cs && (is.null(c1) || is.null(c2)))
        stop("For binary bca/bcm/cs, supply c1 and c2 (or Pi, or p01/p10/pi_z).")
      if (needs_onestep && fix_omega && (is.null(p01) || is.null(p10) || is.null(pi_z)))
        stop("For onestep with fix_omega=TRUE, supply p01, p10, and pi_z.")
    } else {
      needs_bca_bcm_cs <- any(method %in% c("bca", "bcm", "cs"))
      needs_onestep    <- "onestep" %in% method
      if (needs_bca_bcm_cs) {
        if (is.null(Pi) || is.null(pi_z))
          stop("For multicategory bca/bcm/cs, supply Pi and pi_z.")
        Pi   <- as.matrix(Pi)
        pi_z <- as.numeric(pi_z)
        stopifnot(nrow(Pi) == K, ncol(Pi) == K, length(pi_z) == K)
      }
      if (needs_onestep && fix_omega && (is.null(Pi) || is.null(pi_z)))
        stop("For multicategory onestep with fix_omega=TRUE, supply Pi and pi_z.")
    }
  }

  # --- build xi_hat once ---
  if (!is_multinomial) {
    xi_hat <- .mcglm_build_xi_hat(z_hat, x, K)
  }

  # --- fit ---
  results <- list()
  onestep_vcov   <- NULL
  onestep_loglik <- NULL
  naive_glm_fit  <- NULL

  if (is_multinomial) {
    naive_mn <- .mcglm_fit_naive_multinomial(y, z_hat, x, J, K, wt = wt)
    psi      <- naive_mn$coefficients
    results$naive <- psi
    p_total  <- length(psi)

    if ("onestep" %in% method) {
      os <- .mcglm_fit_onestep_multinomial(y, z_hat, x, J, K,
                                           p01 = p01, p10 = p10, pi_z = pi_z,
                                           Pi = Pi, fix_omega = fix_omega,
                                           optim_control = optim_control,
                                           wt = wt)
      results$onestep <- os$coefficients
      onestep_vcov    <- os$vcov
      onestep_loglik  <- os$loglik
    }

  } else if (is_binary) {
    naive <- .mcglm_fit_naive_bin(y, xi_hat, family, wt = wt)
    psi   <- naive$coefficients
    results$naive <- psi
    p_total <- length(psi)
    naive_glm_fit <- naive$glm_fit

    if ("bca" %in% method)
      results$bca <- .mcglm_fit_bca_bin(psi, y, xi_hat, x, family, c1, c2,
                                         iterate = iterate, wt = wt)
    if ("bcm" %in% method)
      results$bcm <- .mcglm_fit_bcm_bin(psi, y, xi_hat, x, family, c1, c2,
                                         iterate = iterate, wt = wt)
    if ("cs"  %in% method)
      results$cs  <- .mcglm_fit_cs_bin(psi, y, xi_hat, x, family, c1, c2,
                                        wt = wt)

    if ("onestep" %in% method) {
      os <- .mcglm_fit_onestep_bin(y, z_hat, x, family, p01, p10, pi_z,
                                   fix_omega = fix_omega,
                                   homoskedastic = homoskedastic,
                                   optim_control = optim_control, wt = wt)
      results$onestep <- os$coefficients
      onestep_vcov    <- os$vcov
      onestep_loglik  <- os$loglik
    }

  } else {
    naive <- .mcglm_fit_naive_multi(y, xi_hat, family, wt = wt)
    psi   <- naive$coefficients
    results$naive <- psi
    p_total <- length(psi)
    naive_glm_fit <- naive$glm_fit

    if ("bca" %in% method)
      results$bca <- .mcglm_fit_bca_multi(psi, y, xi_hat, z_hat, x, K, family,
                                           Pi, pi_z, iterate = iterate, wt = wt)
    if ("bcm" %in% method)
      results$bcm <- .mcglm_fit_bcm_multi(psi, y, xi_hat, z_hat, x, K, family,
                                           Pi, pi_z, iterate = iterate, wt = wt)
    if ("cs"  %in% method)
      results$cs  <- .mcglm_fit_cs_multi(psi, y, xi_hat, z_hat, x, K, family,
                                          Pi, pi_z, wt = wt)

    if ("onestep" %in% method) {
      os <- .mcglm_fit_onestep_multi(y, z_hat, x, K, family, Pi, pi_z,
                                     fix_omega = fix_omega,
                                     homoskedastic = homoskedastic,
                                     optim_control = optim_control, wt = wt)
      results$onestep <- os$coefficients
      onestep_vcov    <- os$vcov
      onestep_loglik  <- os$loglik
    }
  }

  # --- parameter names ---
  if (is_multinomial) {
    s <- K - 1
    r <- ncol(x)
    block_size <- s + r
    nms <- character(p_total)
    for (jj in seq_len(J - 1)) {
      offset <- (jj - 1) * block_size
      if (s == 1) {
        nms[offset + 1] <- paste0("y", jj, ":gamma")
      } else if (s > 1) {
        nms[offset + seq_len(s)] <- paste0("y", jj, ":gamma", seq_len(s))
      }
      nms[offset + s + seq_len(r)] <- paste0("y", jj, ":alpha", seq_len(r) - 1)
    }
  } else if (is_binary) {
    nms <- c("gamma", paste0("alpha", seq_len(ncol(x)) - 1))
  } else {
    nms <- c(paste0("gamma", seq_len(K - 1)),
             paste0("alpha", seq_len(ncol(x)) - 1))
  }
  results <- lapply(results, function(v) {
    v <- as.numeric(v)
    names(v) <- nms
    v
  })

  # --- per-method asymptotic variance ---
  vcov_list <- list()
  if (!is_multinomial) {
    for (nm in names(results)) {
      psi_nm <- unname(results[[nm]])
      V <- tryCatch(
        if (nm == "naive") {
          if (is_binary)
            .mcglm_vcov_naive(psi_nm, y, xi_hat, family, wt = wt)
          else
            .mcglm_vcov_naive_multi(psi_nm, y, xi_hat, z_hat, x, K, family,
                                    wt = wt)
        } else if (nm %in% c("bca", "bcm")) {
          have_probs <- !is.null(p01) && !is.null(p10) && !is.null(pi_z)
          if (is_binary) {
            .mcglm_vcov_bc_bin(psi_nm, y, xi_hat, x, family,
                               p01 = p01, p10 = p10, pi_z = pi_z,
                               psi_naive = unname(results$naive),
                               type = nm,
                               corrected = vcov_corrected && have_probs,
                               wt = wt)
          } else {
            have_multi <- !is.null(Pi) && !is.null(pi_z)
            .mcglm_vcov_bc_multi(psi_nm, y, xi_hat, z_hat, x, K, family,
                                 Pi = Pi, pi_z = pi_z,
                                 psi_naive = unname(results$naive),
                                 type = nm,
                                 corrected = vcov_corrected && have_multi,
                                 wt = wt)
          }
        } else if (nm == "cs") {
          if (is_binary)
            .mcglm_vcov_cs_bin(psi_nm, y, xi_hat, x, family, p01, p10, pi_z,
                               wt = wt)
          else
            .mcglm_vcov_cs_multi(psi_nm, y, xi_hat, z_hat, x, K, family,
                                 Pi, pi_z, wt = wt)
        } else if (nm == "onestep") {
          onestep_vcov
        },
        error = function(e) {
          warning("Variance computation failed for method '", nm, "': ",
                  conditionMessage(e))
          NULL
        }
      )
      if (!is.null(V)) {
        dimnames(V) <- list(nms, nms)
      }
      vcov_list[[nm]] <- V
    }
  } else if (!is.null(onestep_vcov)) {
    vcov_list$onestep <- onestep_vcov
  }

  se_list <- lapply(vcov_list, function(V) {
    if (is.null(V)) return(NULL)
    s <- sqrt(pmax(diag(V), 0))
    names(s) <- rownames(V)
    s
  })

  out <- list(
    coefficients = results,
    vcov         = vcov_list,
    se           = se_list,
    naive_fit    = naive_glm_fit,
    method       = method,
    family       = family,
    K            = K,
    n            = n,
    p            = p_total,
    weights      = wt,
    y            = y,
    z_hat        = z_hat,
    x            = x,
    is_multinomial = is_multinomial
  )
  if (!is_multinomial) out$xi_hat <- xi_hat
  if (is_multinomial)  out$J     <- J

  if (!is.null(onestep_vcov)) {
    out$vcov_onestep   <- onestep_vcov  # kept for backwards compatibility
    out$loglik_onestep <- onestep_loglik
  }

  structure(out, class = "mcglm")
}


#' Default method for an \code{mcglm} object
#' @keywords internal
.mcglm_default_method <- function(object) {
  if (!is.null(object$method) && length(object$method))
    return(object$method[length(object$method)])
  names(object$coefficients)[1]
}

.mcglm_family_string <- function(object) {
  if (is.character(object$family)) return(object$family)
  if (inherits(object$family, "family")) return(object$family$family)
  as.character(object$family)
}


#' Print method for \code{mcglm} fits
#'
#' Mirrors the layout of \code{print.glm}: shows the call, the family,
#' a coefficient table (one column per estimation method), the residual
#' degrees of freedom and (when available) the deviance and AIC of the
#' naive GLM fit.
#' @param x An object of class \code{"mcglm"}.
#' @param digits Number of digits to display.
#' @param ... Unused.
#' @export
print.mcglm <- function(x, digits = max(3L, getOption("digits") - 3L), ...) {
  cat("\nCall:\n")
  if (!is.null(x$call)) print(x$call) else cat("mcglm(...)\n")
  cat("\nFamily: ", .mcglm_family_string(x),
      "  |  n = ", x$n, ", K = ", x$K,
      ", p = ", x$p, "\n", sep = "")
  cat("Methods: ", paste(x$method, collapse = ", "), "\n\n", sep = "")

  cat("Coefficients:\n")
  coefs <- do.call(cbind, x$coefficients)
  colnames(coefs) <- toupper(names(x$coefficients))
  print.default(format(coefs, digits = digits), print.gap = 2L,
                quote = FALSE)

  if (!is.null(x$naive_fit)) {
    rdf <- x$naive_fit$df.residual
    cat("\nDegrees of Freedom:", x$naive_fit$df.null, "Total (i.e. Null); ",
        rdf, "Residual\n")
    cat("Null Deviance:    ",
        format(signif(x$naive_fit$null.deviance, digits)), "\n")
    cat("Residual Deviance:",
        format(signif(x$naive_fit$deviance, digits)),
        " | AIC (naive):", format(signif(stats::AIC(x$naive_fit), digits)),
        "\n")
  }
  if (!is.null(x$loglik_onestep)) {
    cat("logLik (onestep): ", format(signif(x$loglik_onestep, digits)), "\n")
  }
  invisible(x)
}


#' Extract coefficients from an \code{mcglm} fit
#'
#' @param object An \code{mcglm} object.
#' @param method Optional character: which estimator to extract
#'   (\code{"naive"}, \code{"bca"}, \code{"bcm"}, \code{"cs"},
#'   \code{"onestep"}). If \code{NULL}, returns a named list of all
#'   coefficient vectors.
#' @param ... Unused.
#' @export
coef.mcglm <- function(object, method = NULL, ...) {
  if (is.null(method)) return(object$coefficients)
  if (!method %in% names(object$coefficients))
    stop("Method '", method, "' was not fit. Available: ",
         paste(names(object$coefficients), collapse = ", "))
  object$coefficients[[method]]
}


#' Variance-covariance matrix of an \code{mcglm} fit
#'
#' @param object An \code{mcglm} object.
#' @param method Optional character: which estimator to use. Defaults to the
#'   last method fit (e.g. \code{"onestep"} when present, else the most
#'   refined correction available).
#' @param ... Unused.
#' @return A \eqn{p \times p} sandwich variance-covariance matrix.
#' @export
vcov.mcglm <- function(object, method = NULL, ...) {
  if (is.null(object$vcov)) {
    # backwards-compat (older fits stored only vcov_onestep)
    return(object$vcov_onestep)
  }
  if (is.null(method)) method <- .mcglm_default_method(object)
  if (!method %in% names(object$vcov))
    stop("No variance available for method '", method, "'.")
  object$vcov[[method]]
}


#' Summary of an \code{mcglm} fit
#'
#' Returns a Wald-style coefficient table (estimate, standard error,
#' z-value, p-value) for each fitted method, using the asymptotic
#' sandwich variance derived in Battaglia et al. (2025).
#' @param object An \code{mcglm} object.
#' @param ... Unused.
#' @export
summary.mcglm <- function(object, ...) {
  fam_str <- .mcglm_family_string(object)
  ans <- list(
    call    = object$call,
    family  = fam_str,
    n       = object$n,
    p       = object$p,
    K       = object$K,
    method  = object$method,
    coefficients = list(),
    deviance     = if (!is.null(object$naive_fit)) object$naive_fit$deviance,
    df.residual  = if (!is.null(object$naive_fit)) object$naive_fit$df.residual,
    aic_naive    = if (!is.null(object$naive_fit)) stats::AIC(object$naive_fit),
    loglik_onestep = object$loglik_onestep
  )
  for (nm in names(object$coefficients)) {
    est <- object$coefficients[[nm]]
    V   <- if (!is.null(object$vcov)) object$vcov[[nm]] else NULL
    if (!is.null(V)) {
      se <- sqrt(pmax(diag(V), 0))
      z  <- est / se
      pv <- 2 * stats::pnorm(-abs(z))
      tab <- cbind(Estimate = est,
                   `Std. Error` = se,
                   `z value` = z,
                   `Pr(>|z|)` = pv)
    } else {
      tab <- cbind(Estimate = est)
    }
    ans$coefficients[[nm]] <- tab
  }
  class(ans) <- "summary.mcglm"
  ans
}


#' @export
print.summary.mcglm <- function(x,
                                digits = max(3L, getOption("digits") - 3L),
                                signif.stars = getOption("show.signif.stars"),
                                ...) {
  cat("\nCall:\n")
  if (!is.null(x$call)) print(x$call) else cat("mcglm(...)\n")
  cat("\nFamily: ", x$family,
      "  |  n = ", x$n, ", K = ", x$K, ", p = ", x$p, "\n", sep = "")
  cat("Methods: ", paste(x$method, collapse = ", "), "\n", sep = "")

  for (nm in x$method) {
    cat("\n--- ", toupper(nm), " ---\n", sep = "")
    tab <- x$coefficients[[nm]]
    if (is.null(tab)) next
    has_p <- ncol(tab) >= 4L
    stats::printCoefmat(tab, digits = digits,
                        has.Pvalue = has_p, P.values = has_p,
                        signif.stars = signif.stars && has_p,
                        cs.ind = if (has_p) 1:2 else 1L,
                        tst.ind = if (has_p) 3L else integer(0),
                        na.print = "NA")
  }

  if (!is.null(x$deviance)) {
    cat("\nResidual deviance (naive): ",
        format(signif(x$deviance, digits)),
        "  on ", x$df.residual, " degrees of freedom\n", sep = "")
    cat("AIC (naive): ", format(signif(x$aic_naive, digits)), "\n", sep = "")
  }
  if (!is.null(x$loglik_onestep)) {
    cat("logLik (onestep): ", format(signif(x$loglik_onestep, digits)), "\n",
        sep = "")
  }
  if (length(x$coefficients) > 1L) {
    cat("\nBias correction (difference from naive):\n")
    naive <- x$coefficients[["naive"]][, "Estimate"]
    others <- setdiff(names(x$coefficients), "naive")
    diffs <- sapply(others, function(o)
      x$coefficients[[o]][, "Estimate"] - naive)
    if (!is.matrix(diffs)) diffs <- matrix(diffs, nrow = 1L,
                                           dimnames = list(names(naive), others))
    print.default(format(diffs, digits = digits), print.gap = 2L,
                  quote = FALSE)
  }
  invisible(x)
}


#' Standard errors of coefficient estimates
#'
#' @param object An \code{mcglm} object.
#' @param method Optional method name.
#' @return Named numeric vector of standard errors.
#' @export
se.mcglm <- function(object, method = NULL) {
  if (is.null(object$se)) return(sqrt(diag(vcov(object, method = method))))
  if (is.null(method)) method <- .mcglm_default_method(object)
  object$se[[method]]
}


#' Wald confidence intervals for an \code{mcglm} fit
#'
#' @param object An \code{mcglm} object.
#' @param parm Optional names or indices of parameters to return.
#' @param level Coverage level.
#' @param method Optional estimation method (defaults to the last one fit,
#'   e.g. \code{"onestep"} if present).
#' @param ... Unused.
#' @export
confint.mcglm <- function(object, parm, level = 0.95, method = NULL, ...) {
  if (is.null(method)) method <- .mcglm_default_method(object)
  est <- coef(object, method = method)
  V   <- vcov(object, method = method)
  if (is.null(V))
    stop("No variance available for method '", method, "'.")
  se   <- sqrt(pmax(diag(V), 0))
  alpha <- (1 - level) / 2
  q    <- stats::qnorm(1 - alpha)
  ci   <- cbind(est - q * se, est + q * se)
  pct  <- paste0(format(c(alpha, 1 - alpha) * 100,
                        trim = TRUE, scientific = FALSE,
                        digits = 3), " %")
  colnames(ci) <- pct
  rownames(ci) <- names(est)
  if (!missing(parm)) ci <- ci[parm, , drop = FALSE]
  ci
}


#' Fitted values for an \code{mcglm} fit
#'
#' @param object An \code{mcglm} object.
#' @param method Estimation method.
#' @param ... Unused.
#' @export
fitted.mcglm <- function(object, method = NULL, ...) {
  if (isTRUE(object$is_multinomial))
    stop("fitted() not yet implemented for multinomial mcglm fits.")
  if (is.null(method)) method <- .mcglm_default_method(object)
  psi <- coef(object, method = method)
  fam <- .mcglm_get_link_funs(object$family)
  eta <- as.numeric(object$xi_hat %*% unname(psi))
  setNames(fam$mu(eta), seq_along(eta))
}


#' Linear-predictor or response predictions
#'
#' Currently supports in-sample prediction only.
#' @param object An \code{mcglm} object.
#' @param newdata Currently unused. Predictions are computed at the in-sample
#'   proxy design \eqn{\hat\xi_i}.
#' @param type One of \code{"link"}, \code{"response"}.
#' @param method Estimation method.
#' @param ... Unused.
#' @export
predict.mcglm <- function(object, newdata = NULL,
                          type = c("link", "response"),
                          method = NULL, ...) {
  type <- match.arg(type)
  if (!is.null(newdata))
    stop("predict() with 'newdata' not yet supported for mcglm fits.")
  if (isTRUE(object$is_multinomial))
    stop("predict() not yet implemented for multinomial mcglm fits.")
  if (is.null(method)) method <- .mcglm_default_method(object)
  psi <- coef(object, method = method)
  eta <- as.numeric(object$xi_hat %*% unname(psi))
  if (type == "link") return(eta)
  fam <- .mcglm_get_link_funs(object$family)
  fam$mu(eta)
}


#' Residuals for an \code{mcglm} fit
#'
#' @param object An \code{mcglm} object.
#' @param method Estimation method.
#' @param type One of \code{"response"}, \code{"pearson"}, \code{"deviance"}.
#' @param ... Unused.
#' @export
residuals.mcglm <- function(object, method = NULL,
                            type = c("response", "pearson", "deviance"),
                            ...) {
  type <- match.arg(type)
  if (isTRUE(object$is_multinomial))
    stop("residuals() not yet implemented for multinomial mcglm fits.")
  if (is.null(method)) method <- .mcglm_default_method(object)
  fam_funs <- .mcglm_get_link_funs(object$family)
  fam      <- fam_funs$family
  mu_val   <- fitted(object, method = method)
  r        <- object$y - mu_val
  if (type == "response") return(r)
  if (type == "pearson") return(r / sqrt(fam$variance(mu_val)))
  wt <- if (is.null(object$weights)) rep.int(1, length(r)) else object$weights
  d  <- fam$dev.resids(object$y, mu_val, wt = wt)
  sign(r) * sqrt(d)
}


#' Number of observations
#' @param object An \code{mcglm} object.
#' @param ... Unused.
#' @export
nobs.mcglm <- function(object, ...) object$n


#' Family of an \code{mcglm} fit
#' @param object An \code{mcglm} object.
#' @param ... Unused.
#' @export
family.mcglm <- function(object, ...) {
  .mcglm_get_link_funs(object$family)$family
}


#' Formula of an \code{mcglm} fit (NULL for matrix interface)
#' @param x An \code{mcglm} object.
#' @param ... Unused.
#' @export
formula.mcglm <- function(x, ...) x$formula


#' Proxy design matrix used by \code{mcglm}
#'
#' Returns the assembled \eqn{\hat\xi_i = (\hat d_i, x_i)} design matrix
#' (proxy-encoded misclassified covariate plus other covariates).
#' @param object An \code{mcglm} object.
#' @param ... Unused.
#' @export
model.matrix.mcglm <- function(object, ...) object$xi_hat


#' Log-likelihood of an \code{mcglm} fit
#'
#' Returns the naive-GLM log-likelihood for \code{method = "naive"} (the
#' only estimator with a closed-form likelihood for proxy data) or the
#' integrated mixture log-likelihood for \code{method = "onestep"}. Other
#' methods do not correspond to a likelihood; an error is thrown.
#' @param object An \code{mcglm} object.
#' @param method Estimation method.
#' @param ... Unused.
#' @export
logLik.mcglm <- function(object, method = NULL, ...) {
  if (is.null(method))
    method <- if ("onestep" %in% object$method) "onestep" else "naive"
  if (method == "onestep" && !is.null(object$loglik_onestep)) {
    val <- object$loglik_onestep
    df  <- length(coef(object, method = "onestep"))
    attr(val, "df")   <- df
    attr(val, "nobs") <- object$n
    class(val) <- "logLik"
    return(val)
  }
  if (method == "naive" && !is.null(object$naive_fit)) {
    return(stats::logLik(object$naive_fit))
  }
  stop("logLik not defined for method '", method, "'. ",
       "Available: ", paste(intersect(c("naive", "onestep"), object$method),
                            collapse = ", "))
}


#' AIC of an \code{mcglm} fit
#' @param object An \code{mcglm} object.
#' @param ... Additional arguments (ignored).
#' @param k Penalty per parameter (default 2).
#' @export
AIC.mcglm <- function(object, ..., k = 2) {
  ll <- logLik(object)
  -2 * as.numeric(ll) + k * attr(ll, "df")
}


#' BIC of an \code{mcglm} fit
#' @param object An \code{mcglm} object.
#' @param ... Additional arguments (ignored).
#' @export
BIC.mcglm <- function(object, ...) {
  ll <- logLik(object)
  -2 * as.numeric(ll) + log(attr(ll, "nobs")) * attr(ll, "df")
}
