# =========================================================================
# MC-SIMEX internal helpers
# =========================================================================
# These are used by .simex_discrete() in simex.R.
# No exported functions in this file.

#' Build x_mat from a clean formula, preserving I(), interactions, offsets, etc.
#'
#' Replaces the fragile all.vars() + reformulate() approach. Uses model.matrix()
#' on the clean formula and removes columns belonging to mc variables.
#' @param clean_formula the formula with mc() wrappers stripped (bare variable names remain)
#' @param mc_variables character vector of mc variable names to exclude
#' @param data the data frame
#' @return a list with x_mat (the non-mc part of the model matrix) and
#'   x_terms (the terms object, for use in predict)
#' @keywords internal
.build_x_mat <- function(clean_formula, mc_variables, data) {
  tt <- terms(clean_formula)
  # Drop response so this works with newdata that lacks the response variable
  tt <- delete.response(tt)
  mf <- model.frame(tt, data = data, na.action = na.pass)
  full_mm <- model.matrix(tt, mf)

  # Identify columns generated by mc variables (factor dummies)
  # model.matrix names factor columns as "varnamelevel", so we match on the

  # variable name prefix. We must be careful not to match variables that
  # merely start with the same prefix, so we use the assignment attribute.
  asgn <- attr(full_mm, "assign")
  term_labels <- attr(tt, "term.labels")

  # Find which term indices correspond to mc variables (exact match)
  mc_term_idx <- which(term_labels %in% mc_variables)

  # Columns to drop: those assigned to mc terms

  mc_cols <- which(asgn %in% mc_term_idx)

  if (length(mc_cols) > 0) {
    x_mat <- full_mm[, -mc_cols, drop = FALSE]
  } else {
    x_mat <- full_mm
  }

  list(x_mat = x_mat, x_terms = tt, x_model_frame = mf)
}

#' Build design matrix [dummies(z, K-1), x] in R (mirrors C++ build_design)
#' @keywords internal
.build_xi_hat <- function(z_hat, x_mat, K) {
  n <- length(z_hat)
  s <- K - 1L
  dummies <- matrix(0, n, s)
  for (k in seq_len(s)) {
    dummies[, k] <- as.numeric(z_hat == k)
  }
  cbind(dummies, x_mat)
}

#' Generate parameter names for the SIMEX model (single mc variable)
#' @keywords internal
.make_param_names <- function(z_levels, x_mat, K) {
  if (K == 2L) {
    dummy_names <- z_levels[2]
  } else {
    dummy_names <- z_levels[-1]
  }
  c(dummy_names, colnames(x_mat))
}

#' Build design matrix for multiple mc variables
#' [dummies_z1(K1-1) | dummies_z2(K2-1) | ... | x_mat]
#' @keywords internal
.build_multi_xi_hat <- function(z_hats, K_vec, x_mat) {
  n <- length(z_hats[[1]])
  n_mc <- length(z_hats)
  dummy_blocks <- vector("list", n_mc)
  for (j in seq_len(n_mc)) {
    sj <- K_vec[j] - 1L
    dummies <- matrix(0, n, sj)
    for (k in seq_len(sj)) {
      dummies[, k] <- as.numeric(z_hats[[j]] == k)
    }
    dummy_blocks[[j]] <- dummies
  }
  do.call(cbind, c(dummy_blocks, list(x_mat)))
}

#' Generate parameter names for multiple mc variables
#' @keywords internal
.make_multi_param_names <- function(z_levels_list, K_vec, x_mat) {
  dummy_names <- character(0)
  var_names <- names(z_levels_list)
  for (j in seq_along(z_levels_list)) {
    levs <- z_levels_list[[j]]
    prefix <- var_names[j]
    if (K_vec[j] == 2L) {
      dummy_names <- c(dummy_names, paste0(prefix, levs[2]))
    } else {
      dummy_names <- c(dummy_names, paste0(prefix, levs[-1]))
    }
  }
  c(dummy_names, colnames(x_mat))
}


# =========================================================================
# Improved MC-SIMEX helpers (Sevilimedu & Yu, 2026)
# =========================================================================

#' Estimate marginal probability P(X=1) from observed data and Pi
#' @keywords internal
.estimate_pi_x <- function(z_hat, Pi) {
  p_w1 <- mean(z_hat == 1L)
  pi_00 <- Pi[1, 1]
  pi_11 <- Pi[2, 2]
  delta <- pi_00 + pi_11 - 1
  if (abs(delta) < 1e-10)
    stop("Misclassification matrix is degenerate (pi_00 + pi_11 = 1)")
  pi_x <- (p_w1 - 1 + pi_00) / delta
  max(1e-6, min(1 - 1e-6, pi_x))
}

#' Estimate latent category probabilities from observed categories and Pi
#' @keywords internal
.estimate_pi_vec <- function(z_hat, Pi, wt = NULL, eps = 1e-6) {
  K <- nrow(Pi)
  if (is.null(wt)) wt <- rep(1, length(z_hat))
  wt <- as.numeric(wt)
  N <- sum(wt)
  if (!is.finite(N) || N <= 0)
    stop("weights must have positive total mass.", call. = FALSE)

  p_obs <- numeric(K)
  for (k in seq_len(K)) {
    p_obs[k] <- sum(wt[z_hat == (k - 1L)]) / N
  }

  pi_vec <- tryCatch(
    solve(Pi, p_obs),
    error = function(e) {
      stop("Misclassification matrix is singular; latent prevalences ",
           "are not identifiable.", call. = FALSE)
    }
  )
  if (any(!is.finite(pi_vec)))
    stop("Could not estimate finite latent category probabilities.",
         call. = FALSE)

  pi_vec <- pmax(pi_vec, eps)
  pi_vec / sum(pi_vec)
}

#' Compute matrix power Pi^power
#'
#' Uses exact matrix multiplication for non-negative integer powers and
#' the principal branch of the eigendecomposition otherwise. Pi need not
#' be symmetric; complex eigenvalues are handled via complex arithmetic
#' (the result is real for any column-stochastic Pi raised to a real
#' power, since complex eigenvalues come in conjugate pairs).
#' @keywords internal
.mat_power_r <- function(Pi, power) {
  K <- nrow(Pi)
  if (power == 0) return(diag(K))
  if (power == 1) return(Pi)

  # Integer powers >= 1: pure matrix multiplication, no eigendecomposition.
  if (isTRUE(all.equal(power, round(power))) && power >= 1) {
    Pp <- Pi
    for (k in seq_len(round(power) - 1L)) Pp <- Pp %*% Pi
    return(Pp)
  }

  # Fractional / negative powers: principal branch via eigendecomposition.
  ev <- eigen(Pi)
  d  <- as.complex(ev$values)
  V  <- ev$vectors
  V_inv <- tryCatch(solve(V),
                    error = function(e)
                      MASS::ginv(V, tol = sqrt(.Machine$double.eps)))

  d_pow <- d^power                      # principal branch (handles complex)
  Pi_pow <- V %*% diag(d_pow, K) %*% V_inv

  # For column-stochastic Pi, the result is real up to numerical noise.
  imag_scale <- max(abs(Im(Pi_pow)))
  real_scale <- max(abs(Re(Pi_pow)))
  if (!is.finite(imag_scale) || imag_scale > 1e-8 * max(1, real_scale))
    stop("Pi^power has a non-negligible imaginary part; the misclassification ",
         "matrix is not diagonalisable to a real power.", call. = FALSE)

  zapsmall(Re(Pi_pow))
}

#' Compute correction factor c_lambda for the improved MC-SIMEX
#' @keywords internal
.compute_c_lambda <- function(Pi, pi_x, lambda) {
  sapply(lambda, function(lam) {
    Pi_lam <- .mat_power_r(Pi, 1 + lam)
    pi_00_lam <- Pi_lam[1, 1]
    pi_11_lam <- Pi_lam[2, 2]
    delta_lam <- pi_00_lam + pi_11_lam - 1
    if (abs(delta_lam) < 1e-10) return(NA_real_)
    denominator <- pi_x * (1 - pi_x) * delta_lam
    numerator <- (pi_00_lam - pi_x * delta_lam) *
                 (1 - pi_00_lam + delta_lam * pi_x)
    if (abs(denominator) < 1e-10) return(NA_real_)
    numerator / denominator
  })
}

#' Compute intercept correction factor for the improved MC-SIMEX
#' @keywords internal
.compute_intercept_correction <- function(Pi, pi_x, lambda) {
  sapply(lambda, function(lam) {
    Pi_lam <- .mat_power_r(Pi, 1 + lam)
    pi_00_lam <- Pi_lam[1, 1]
    pi_11_lam <- Pi_lam[2, 2]
    delta_lam <- pi_00_lam + pi_11_lam - 1
    denom <- pi_00_lam - delta_lam * pi_x
    if (abs(denom) < 1e-10) return(0)
    (1 - pi_11_lam) * pi_x / denom
  })
}

#' Compute K-level correction components for improved MC-SIMEX
#' @keywords internal
.compute_k_correction <- function(Pi, pi_vec, lambda) {
  K <- nrow(Pi)
  s <- K - 1L

  lapply(lambda, function(lam) {
    M <- .mat_power_r(Pi, 1 + lam)
    q <- as.numeric(M %*% pi_vec)

    if (any(q <= 0) || any(!is.finite(q)))
      stop("Observed category probabilities implied by the correction ",
           "matrix must be positive.", call. = FALSE)

    pi_plus <- pi_vec[-1]
    q_plus <- q[-1]
    Sigma_RR <- diag(q_plus, nrow = s) - tcrossprod(q_plus)
    Sigma_RD <- M[-1, -1, drop = FALSE] %*% diag(pi_plus, nrow = s) -
      tcrossprod(q_plus, pi_plus)

    C <- tryCatch(
      solve(Sigma_RD, Sigma_RR),
      error = function(e) {
        stop("K-level improved MC-SIMEX correction is not identifiable; ",
             "Sigma_RD is singular.", call. = FALSE)
      }
    )

    alpha <- pi_plus * M[1, -1] / q[1]
    list(
      C = C,
      alpha = alpha,
      M = M,
      q = q,
      Sigma_RR = Sigma_RR,
      Sigma_RD = Sigma_RD
    )
  })
}

#' Apply K-level improved correction to coefficient rows
#' @keywords internal
.apply_k_improved_correction <- function(theta_mat, C, alpha,
                                         intercept_idx = integer(0)) {
  theta_mat <- as.matrix(theta_mat)
  s <- nrow(C)
  corrected <- theta_mat
  beta_z <- theta_mat[, seq_len(s), drop = FALSE] %*% t(C)
  corrected[, seq_len(s)] <- beta_z

  if (length(intercept_idx) == 1L) {
    corrected[, intercept_idx] <- theta_mat[, intercept_idx] -
      as.numeric(beta_z %*% alpha)
  }

  corrected
}

#' Linear transformation matrix for fixed-Pi improved MC-SIMEX
#' @keywords internal
.k_improved_transform <- function(p, C, alpha, intercept_idx = integer(0)) {
  s <- nrow(C)
  T <- diag(p)
  T[seq_len(s), seq_len(s)] <- C

  if (length(intercept_idx) == 1L) {
    T[intercept_idx, seq_len(s)] <- -as.numeric(alpha %*% C)
    T[intercept_idx, intercept_idx] <- 1
  }

  T
}

#' Variance estimation for fixed-Pi K-level improved MC-SIMEX
#' @keywords internal
.variance_k_improved <- function(theta_list, naive_refit, transform,
                                 lambda, B, p) {
  if (length(lambda) * B == 1L) {
    V <- vcov(naive_refit)
    V <- unname(V)
    return(transform %*% V %*% t(transform))
  }

  all_corrected <- do.call(rbind, theta_list)
  cov(all_corrected) / (length(lambda) * B)
}

#' Find optimal lambda that minimizes |c_lambda|
#' @keywords internal
.find_optimal_lambda <- function(Pi, pi_x, grid = seq(0.1, 3, by = 0.01)) {
  c_values <- .compute_c_lambda(Pi, pi_x, grid)
  valid <- !is.na(c_values) & is.finite(c_values)
  if (!any(valid)) stop("Cannot find valid lambda for the improved method")
  grid[valid][which.min(abs(c_values[valid]))]
}

#' Variance estimation for the improved MC-SIMEX
#' @keywords internal
.variance_improved <- function(theta_list, corrected_coefs, c_lam_vec,
                               n_lambda, B, p, naive_fit, xi_hat, y, wt, fam) {
  N <- sum(wt)
  n <- length(y)
  if (n_lambda * B == 1) {
    psi_mean <- corrected_coefs
    eta_m <- as.numeric(xi_hat %*% psi_mean)
    w_m <- fam$mu_dot(eta_m)
    eps_m <- y - fam$mu(eta_m)
    A_m <- crossprod(xi_hat * (wt * w_m), xi_hat) / N
    C_m <- crossprod(xi_hat * (wt * eps_m), xi_hat * eps_m) / N
    A_m_inv <- tryCatch(solve(A_m), error = function(e) MASS::ginv(A_m))
    V_model <- A_m_inv %*% C_m %*% A_m_inv / N
    V_scaled <- V_model * c_lam_vec[1]^2
    return(V_scaled)
  }
  all_corrected <- do.call(rbind, theta_list)
  cov(all_corrected) / (n_lambda * B)
}
