# =========================================================================
# MC-SIMEX: Misclassification Simulation-Extrapolation
# =========================================================================

#' MC-SIMEX estimator for GLMs with misclassified covariates
#'
#' Implements the Misclassification SIMEX method of Kuchenhoff, Mwalili and
#' Lesaffre (2006). The simulation step runs in C++ for high performance.
#' Supports Gaussian, Poisson, and Binomial GLM families.
#'
#' @param formula a formula describing the model (as in \code{\link{glm}}).
#' @param family a family object (e.g. \code{poisson()}, \code{binomial()}).
#'   Default: \code{gaussian()}.
#' @param data a data frame containing the variables in the formula.
#' @param SIMEXvariable character vector naming the misclassified factor
#'   variable(s) in \code{data}.
#' @param mc.matrix misclassification matrix (K x K) or a named list of
#'   matrices when multiple variables are misclassified. Columns must sum to 1:
#'   \code{mc.matrix[j,l] = P(Z* = j | Z = l)}.
#' @param lambda numeric vector of SIMEX exponents (default:
#'   \code{c(0.5, 1, 1.5, 2)}).
#' @param B number of simulation replicates per lambda level (default: 200).
#' @param extrapolation extrapolation method: \code{"quadratic"} (default),
#'   \code{"linear"}, or \code{"loglinear"}.
#' @param jackknife logical or character. If \code{TRUE}, compute jackknife
#'   variance using the same extrapolation method. If a character string,
#'   use that method for variance extrapolation. \code{FALSE} to skip.
#' @param weights optional prior weights (as in \code{\link{glm}}).
#' @param seed random seed for reproducibility (default: 42).
#'
#' @return An object of class \code{"mcsimex"} with components mimicking
#'   \code{\link{glm}} output:
#'   \describe{
#'     \item{coefficients}{Named vector of SIMEX-corrected coefficients.}
#'     \item{naive.coefficients}{Coefficients from the naive (uncorrected) model.}
#'     \item{residuals}{Working residuals.}
#'     \item{fitted.values}{Fitted values from the corrected model.}
#'     \item{family}{The family object.}
#'     \item{formula}{The model formula.}
#'     \item{call}{The matched call.}
#'     \item{data}{The data used.}
#'     \item{vcov}{Jackknife variance-covariance matrix (if requested).}
#'     \item{SIMEX.estimates}{Matrix of averaged estimates at each lambda level.}
#'     \item{theta}{List of B x p matrices of raw simulation estimates.}
#'     \item{extrapolation}{Fitted extrapolation model(s).}
#'     \item{lambda}{Lambda vector used (including 0).}
#'     \item{B}{Number of simulation replicates.}
#'     \item{SIMEXvariable}{Name(s) of the misclassified variable(s).}
#'     \item{mc.matrix}{The misclassification matrix/matrices.}
#'     \item{naive.model}{The naive \code{glm} fit.}
#'     \item{extrapolation.method}{Extrapolation method used.}
#'   }
#'
#' @details
#' The MC-SIMEX algorithm proceeds in two steps:
#'
#' \strong{Simulation step}: For each \eqn{\lambda} in the lambda grid, the
#' misclassification matrix is raised to the power \eqn{\lambda} via
#' eigendecomposition (\eqn{\Pi^\lambda = V \Lambda^\lambda V^{-1}}), and B
#' replicates of the misclassified covariate are generated by sampling from
#' the columns of \eqn{\Pi^\lambda}. A GLM is refitted to each replicate.
#' This loop runs in compiled C++ code for speed.
#'
#' \strong{Extrapolation step}: The averaged coefficient estimates are modelled
#' as a function of lambda and extrapolated to \eqn{\lambda = -1} (no
#' misclassification). Supported extrapolation functions:
#' \itemize{
#'   \item \code{"linear"}: \eqn{\theta(\lambda) = \gamma_0 + \gamma_1 \lambda}
#'   \item \code{"quadratic"}: \eqn{\theta(\lambda) = \gamma_0 + \gamma_1 \lambda + \gamma_2 \lambda^2}
#'   \item \code{"loglinear"}: \eqn{\theta(\lambda) = \exp(\gamma_0 + \gamma_1 \lambda)}
#' }
#'
#' @references
#' Kuchenhoff, H., Mwalili, S. M. and Lesaffre, E. (2006).
#' A general method for dealing with misclassification in regression: The
#' misclassification SIMEX. \emph{Biometrics}, 62(1), 85--96.
#'
#' Kuchenhoff, H., Lederer, W. and Lesaffre, E. (2007).
#' Asymptotic variance estimation for the misclassification SIMEX.
#' \emph{Computational Statistics & Data Analysis}, 51, 6197--6211.
#'
#' @examples
#' # Generate data with misclassified binary covariate
#' set.seed(42)
#' n <- 2000
#' x <- rnorm(n)
#' z <- rbinom(n, 1, 0.4)
#' y <- rpois(n, exp(0.5 + 0.8 * z + 0.3 * x))
#'
#' # Misclassify z
#' p01 <- 0.10; p10 <- 0.15
#' z_star <- z
#' z_star[z == 0] <- rbinom(sum(z == 0), 1, p01)
#' z_star[z == 1] <- 1 - rbinom(sum(z == 1), 1, p10)
#'
#' df <- data.frame(y = y, z_star = factor(z_star), x = x)
#' Pi <- matrix(c(1 - p01, p01, p10, 1 - p10), 2, 2)
#'
#' fit <- mcsimex(y ~ z_star + x, family = poisson(), data = df,
#'                SIMEXvariable = "z_star", mc.matrix = Pi, B = 100)
#' summary(fit)
#'
#' @export
mcsimex <- function(formula, family = gaussian(), data,
                    SIMEXvariable, mc.matrix,
                    lambda = c(0.5, 1, 1.5, 2),
                    B = 200L,
                    extrapolation = c("quadratic", "linear", "loglinear"),
                    jackknife = TRUE,
                    weights = NULL,
                    seed = 42L) {

  cl <- match.call()
  extrapolation <- match.arg(extrapolation)

  # --- resolve family ---
  if (is.character(family))
    family <- get(family, mode = "function", envir = parent.frame())()
  if (is.function(family)) family <- family()
  if (is.null(family$family))
    stop("'family' not recognized")

  dist_code <- family_to_dist_code(family)

  # --- validate SIMEXvariable ---
  if (!is.character(SIMEXvariable))
    stop("SIMEXvariable must be a character string")
  if (length(SIMEXvariable) != 1L)
    stop("Currently only one SIMEXvariable is supported for MC-SIMEX")

  # --- ensure factor ---
  if (!is.factor(data[[SIMEXvariable]]))
    data[[SIMEXvariable]] <- factor(data[[SIMEXvariable]])

  # --- validate mc.matrix ---
  if (is.matrix(mc.matrix)) {
    mc_list <- list(mc.matrix)
    names(mc_list) <- SIMEXvariable
  } else if (is.list(mc.matrix)) {
    mc_list <- mc.matrix
  } else {
    stop("mc.matrix must be a matrix or named list of matrices")
  }

  Pi <- as.matrix(mc_list[[SIMEXvariable]])
  K <- nrow(Pi)
  stopifnot(ncol(Pi) == K)

  col_sums <- colSums(Pi)
  if (any(abs(col_sums - 1) > 1e-6))
    stop("Columns of mc.matrix must sum to 1 (got: ",
         paste(round(col_sums, 4), collapse = ", "), ")")

  # --- fit naive model ---
  if (!is.null(weights)) {
    naive_fit <- glm(formula, family = family, data = data, weights = weights,
                     x = TRUE, y = TRUE)
  } else {
    naive_fit <- glm(formula, family = family, data = data,
                     x = TRUE, y = TRUE)
  }

  # --- extract data components for C++ ---
  y <- naive_fit$y
  n <- length(y)
  z_factor <- data[[SIMEXvariable]]
  z_levels <- levels(z_factor)

  if (length(z_levels) != K)
    stop("Number of levels in SIMEXvariable (", length(z_levels),
         ") does not match mc.matrix dimensions (", K, ")")

  # Convert factor to 0-based integer
  z_hat <- as.integer(z_factor) - 1L

  # Build covariate matrix x (all terms except SIMEXvariable dummies)
  # Strategy: build model matrix excluding SIMEXvariable, keeping intercept + other vars
  other_terms <- setdiff(all.vars(formula)[-1], SIMEXvariable)
  if (length(other_terms) > 0) {
    other_formula <- reformulate(other_terms, intercept = TRUE)
    x_mat <- model.matrix(other_formula, data = data)
  } else {
    x_mat <- matrix(1, nrow = n, ncol = 1)
    colnames(x_mat) <- "(Intercept)"
  }

  # Weights
  wt <- if (is.null(weights)) rep(1.0, n) else as.numeric(weights)

  lambda <- sort(as.numeric(lambda))
  B <- as.integer(B)
  n_lambda <- length(lambda)

  # --- naive coefficients (from the C++ design matrix layout) ---
  # C++ design: [dummies(z, K-1), x_mat]
  # Build this in R for the naive fit too
  xi_hat <- .build_xi_hat(z_hat, x_mat, K)
  p <- ncol(xi_hat)

  fam <- get_link_funs(family)
  dat_naive <- data.frame(y = y, xi_hat)
  naive_refit <- glm(y ~ . - 1, data = dat_naive, family = family, weights = wt)
  psi_naive <- unname(coef(naive_refit))

  # Parameter names
  nms <- .make_param_names(z_levels, x_mat, K)
  names(psi_naive) <- nms

  # --- simulation step (C++) ---
  sim_result <- mcsimex_sim_cpp(y, z_hat, x_mat, Pi, K, dist_code,
                                lambda, B, wt, as.integer(seed))

  # Reshape: list of B x p matrices (one per lambda)
  theta_list <- vector("list", n_lambda)
  avg_estimates <- matrix(0, n_lambda, p)
  for (l in seq_len(n_lambda)) {
    rows <- ((l - 1) * B + 1):(l * B)
    theta_mat <- sim_result[rows, , drop = FALSE]
    colnames(theta_mat) <- nms
    theta_list[[l]] <- theta_mat
    avg_estimates[l, ] <- colMeans(theta_mat)
  }
  names(theta_list) <- paste0("lambda_", lambda)

  # Stack: lambda=0 (naive) + simulation averages
  all_lambda <- c(0, lambda)
  all_estimates <- rbind(psi_naive, avg_estimates)
  rownames(all_estimates) <- paste0("lambda_", all_lambda)
  colnames(all_estimates) <- nms

  # --- extrapolation step ---
  extrap_result <- extrapolate_simex(all_lambda, all_estimates, extrapolation)

  # --- jackknife variance ---
  vcov_jk <- NULL
  if (!isFALSE(jackknife)) {
    jk_method <- if (is.character(jackknife)) jackknife else extrapolation
    vcov_jk <- jackknife_variance_mcsimex(theta_list, psi_naive, naive_refit,
                                          lambda, jk_method, fam, xi_hat, y, wt)
    rownames(vcov_jk) <- colnames(vcov_jk) <- nms
  }

  # --- fitted values and residuals ---
  corrected_coefs <- extrap_result$coefficients
  eta_corrected <- as.numeric(xi_hat %*% corrected_coefs)
  fitted_vals <- family$linkinv(eta_corrected)
  resids <- y - fitted_vals

  # --- build output object ---
  out <- structure(
    list(
      coefficients       = corrected_coefs,
      naive.coefficients = psi_naive,
      residuals          = resids,
      fitted.values      = fitted_vals,
      family             = family,
      formula            = formula,
      call               = cl,
      data               = data,
      vcov               = vcov_jk,
      SIMEX.estimates    = all_estimates,
      theta              = theta_list,
      extrapolation      = extrap_result$model,
      lambda             = all_lambda,
      B                  = B,
      n                  = n,
      p                  = p,
      SIMEXvariable      = SIMEXvariable,
      mc.matrix          = mc_list,
      naive.model        = naive_fit,
      extrapolation.method = extrapolation
    ),
    class = "mcsimex"
  )
  out
}


# =========================================================================
# Internal helpers
# =========================================================================

#' Build design matrix [dummies(z, K-1), x] in R (mirrors C++ build_design)
#' @keywords internal
.build_xi_hat <- function(z_hat, x_mat, K) {
  n <- length(z_hat)
  s <- K - 1L
  dummies <- matrix(0, n, s)
  for (k in seq_len(s)) {
    dummies[, k] <- as.numeric(z_hat == k)
  }
  cbind(dummies, x_mat)
}

#' Generate parameter names for the SIMEX model
#' @keywords internal
.make_param_names <- function(z_levels, x_mat, K) {
  if (K == 2L) {
    dummy_names <- z_levels[2]
  } else {
    dummy_names <- z_levels[-1]
  }
  c(dummy_names, colnames(x_mat))
}


# =========================================================================
# S3 methods for class "mcsimex"
# =========================================================================

#' @export
print.mcsimex <- function(x, digits = max(3, getOption("digits") - 3), ...) {
  cat("\nCall:\n")
  print(x$call)
  cat("\nMC-SIMEX corrected coefficients:\n")
  print.default(format(coef(x), digits = digits), print.gap = 2,
                quote = FALSE)
  cat("\n")
  invisible(x)
}


#' @export
summary.mcsimex <- function(object, ...) {
  est <- coef(object)
  p.names <- names(est)
  n <- object$n
  p <- length(est)
  rdf <- n - p

  ans <- list()
  ans$call <- object$call
  ans$family <- object$family
  ans$formula <- object$formula
  ans$SIMEXvariable <- object$SIMEXvariable
  ans$mc.matrix <- object$mc.matrix
  ans$lambda <- object$lambda
  ans$B <- object$B
  ans$extrapolation.method <- object$extrapolation.method
  ans$SIMEX.estimates <- object$SIMEX.estimates
  ans$naive.coefficients <- object$naive.coefficients
  ans$residuals <- object$residuals
  ans$n <- n
  ans$df.residual <- rdf

  if (!is.null(object$vcov)) {
    se <- sqrt(pmax(diag(object$vcov), 0))
    tval <- est / se
    pval <- 2 * pt(abs(tval), rdf, lower.tail = FALSE)
    ans$coefficients <- cbind(
      Estimate = est, `Std. Error` = se,
      `t value` = tval, `Pr(>|t|)` = pval
    )
    rownames(ans$coefficients) <- p.names
  } else {
    ans$coefficients <- cbind(Estimate = est)
    rownames(ans$coefficients) <- p.names
  }

  class(ans) <- "summary.mcsimex"
  ans
}


#' @export
print.summary.mcsimex <- function(x,
                                  digits = max(3, getOption("digits") - 3),
                                  ...) {
  cat("\nCall:\n")
  print(x$call)
  cat("\nFamily:", x$family$family, "\n")
  cat("SIMEX variable:", x$SIMEXvariable, "\n")
  cat("Extrapolation:", x$extrapolation.method, "\n")
  cat("Lambda grid:", paste(x$lambda, collapse = ", "), "\n")
  cat("B =", x$B, ", n =", x$n, "\n")

  if (!is.null(x$residuals)) {
    cat("\nResiduals:\n")
    rq <- quantile(x$residuals, na.rm = TRUE)
    names(rq) <- c("Min", "1Q", "Median", "3Q", "Max")
    print(rq, digits = digits)
  }

  cat("\nNaive coefficients:\n")
  print(round(x$naive.coefficients, digits))

  cat("\nMC-SIMEX corrected coefficients:\n")
  if (ncol(x$coefficients) > 1) {
    printCoefmat(x$coefficients, digits = digits)
  } else {
    print(round(x$coefficients, digits))
  }
  cat("\n")
  invisible(x)
}


#' @export
plot.mcsimex <- function(x,
                         xlab = expression(1 + lambda),
                         ylab = NULL,
                         ask = FALSE,
                         show = NULL, ...) {
  old.par <- par(no.readonly = TRUE)
  on.exit(par(old.par))
  if (ask) par(ask = TRUE)

  b <- x$SIMEX.estimates
  p <- ncol(b)
  p.names <- colnames(b)
  lam <- x$lambda

  if (is.null(ylab)) ylab <- p.names
  if (is.null(show)) show <- rep(TRUE, p)

  a <- seq(-1, max(lam), by = 0.01)

  for (j in seq_len(p)) {
    if (!show[j]) next

    # Predict from extrapolation model
    fit_j <- x$extrapolation[[j]]
    nd <- data.frame(lambda = a)
    if (x$extrapolation.method == "loglinear") {
      offset <- attr(fit_j, "loglinear_offset")
      if (is.null(offset)) offset <- 0
      d <- exp(predict(fit_j, newdata = nd)) - offset
    } else {
      d <- predict(fit_j, newdata = nd)
    }

    plot(lam + 1, b[, j], xlab = xlab, ylab = ylab[j], type = "n",
         main = p.names[j], ...)
    # Simulation points (lambda > 0)
    points(lam[-1] + 1, b[-1, j], pch = 19)
    # Naive point (lambda = 0)
    points(lam[1] + 1, b[1, j], pch = 1)
    # Extrapolation curve
    lines(a[a >= 0] + 1, d[a >= 0])
    lines(a[a < 0] + 1, d[a < 0], lty = 2)
    # SIMEX estimate at lambda = -1
    points(0, x$coefficients[j], pch = 4, cex = 1.5, col = "red")
  }
}


#' @export
predict.mcsimex <- function(object, newdata = NULL, type = "response", ...) {
  if (is.null(newdata)) {
    if (type == "link") {
      return(object$family$linkfun(object$fitted.values))
    }
    return(object$fitted.values)
  }

  # Build design matrix for new data
  if (!is.factor(newdata[[object$SIMEXvariable]]))
    newdata[[object$SIMEXvariable]] <- factor(newdata[[object$SIMEXvariable]])

  z_new <- as.integer(newdata[[object$SIMEXvariable]]) - 1L
  K <- object$mc.matrix[[object$SIMEXvariable]] |> nrow()
  other_terms <- setdiff(all.vars(object$formula)[-1], object$SIMEXvariable)
  if (length(other_terms) > 0) {
    other_formula <- reformulate(other_terms, intercept = TRUE)
    x_new <- model.matrix(other_formula, data = newdata)
  } else {
    x_new <- matrix(1, nrow = nrow(newdata), ncol = 1)
  }
  xi_new <- .build_xi_hat(z_new, x_new, K)

  eta <- as.numeric(xi_new %*% object$coefficients)
  if (type == "link") return(eta)
  object$family$linkinv(eta)
}


#' @export
coef.mcsimex <- function(object, ...) object$coefficients

#' @export
vcov.mcsimex <- function(object, ...) object$vcov

#' @export
residuals.mcsimex <- function(object, ...) object$residuals

#' @export
fitted.mcsimex <- function(object, ...) object$fitted.values

#' @export
nobs.mcsimex <- function(object, ...) object$n

#' @export
family.mcsimex <- function(object, ...) object$family

#' @export
formula.mcsimex <- function(x, ...) x$formula

#' @export
confint.mcsimex <- function(object, parm, level = 0.95, ...) {
  cf <- coef(object)
  if (is.null(object$vcov))
    stop("No variance estimates available. Rerun with jackknife = TRUE.")

  ses <- sqrt(pmax(diag(object$vcov), 0))
  a <- (1 - level) / 2
  fac <- qnorm(c(a, 1 - a))

  pnames <- names(cf)
  if (missing(parm)) {
    parm <- pnames
  } else if (is.numeric(parm)) {
    parm <- pnames[parm]
  }

  ci <- cbind(cf[parm] + fac[1] * ses[parm],
              cf[parm] + fac[2] * ses[parm])
  colnames(ci) <- paste0(format(100 * c(a, 1 - a), trim = TRUE), " %")
  ci
}
